# Generated by Django 3.0.8 on 2020-07-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0002_remove_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published',
            new_name='pub_date',
        ),
    ]
